name: Raspagem e Notificação Automática

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora no minuto 0
  workflow_dispatch:      # Permite execução manual pelo GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest  # Ambiente padrão do GitHub Actions
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Atualizar pip
        run: python -m pip install --upgrade pip
        
      - name: Instalar dependências
        run: python -m pip install -r requirements.txt
        
      - name: Criar arquivo de credenciais
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > credentials.json
        shell: bash
        
      - name: Executar script dentro do horário (8h às 18h BRT)
        run: |
          CURRENT_HOUR=$(TZ='America/Sao_Paulo' date +'%H')
          if [ "$CURRENT_HOUR" -ge 8 ] && [ "$CURRENT_HOUR" -lt 18 ]; then
            echo "⏱️ Executando raspagem às $CURRENT_HOUR horas..."
            python raspagem_noticias.py
          else
            echo "⏳ Fora do horário de execução (atual: $CURRENT_HOUR BRT)"
          fi
        shell: bash
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
          SHEET_ID: ${{ secrets.SHEET_ID }}
