name: Raspagem e Notificação Automática

on:
  schedule:
    - cron: '0 10,20 * * *'
  workflow_dispatch:  # Permite a execução manual do workflow através da interface do GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest  # Define o sistema operacional do runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Ação para verificar o código do seu repositório

    - name: Set up Python
      uses: actions/setup-python@v4  # Ação para configurar o ambiente Python
      with:
        python-version: '3.x'  # Especifique a versão do Python

    - name: Install dependencies
      run: python -m pip install -r requirements.txt  # Instala as dependências do arquivo requirements.txt

    - name: Create credentials file
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > credentials.json
      shell: bash  # Cria um arquivo de credenciais para autenticação com o Google

    - name: Execute script
      run: python RASPAGEMGOV.py  # Executa o script Python
      env:  # Configura as variáveis de ambiente necessárias para o script
        PLANILHA: ${{ secrets.PLANILHA }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
