name: Raspagem e Salvamento Automático

on:
  schedule:
    - cron: '0 10,19 * * *'  # Executa às 10:00 e 19:00 UTC
  workflow_dispatch:

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client requests beautifulsoup4

    - name: Create Credentials File
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > credentials.json

    - name: Run Scraper
      run: python RASPAGEMGOV.py
      env:
        PLANILHA: ${{ secrets.PLANILHA }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
